name: solace-vmr-warden-deployment
director_uuid: <%= `bosh status --uuid` %>

releases:
- name: docker
  version: latest
- name: solace-vmr
  version: latest

compilation:
  workers: 1
  network: test-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

resource_pools:
- name: common-resource-pool
  network: test-network
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    name: random

networks:
- name: test-network
  type: manual
  subnets:
  - range: 10.244.0.0/28
    gateway: 10.244.0.1
    static:
      - 10.244.0.2
      - 10.244.0.3
    cloud_properties:
      name: random
  - range: 10.244.0.16/28
    gateway: 10.244.0.17
    static: []
    cloud_properties:
      name: random

jobs:
- name: dedicated-vmr-job
  templates:
  -  {name: docker, release: docker}
  -  {name: prepare_vmr, release: solace-vmr}
  -  {name: containers, release: docker}
  instances: 1
  persistent_disk: 20480
  resource_pool: common-resource-pool
  networks:
  - name: test-network
    static_ips:
      - 10.244.0.3
  properties:
    containers:
      - name: solace
        image: solace-bosh
        dockerfile: |
          FROM solace-app:latest

          RUN \
            echo 'u4EANiNxwS6C' | passwd --stdin admin && \
            echo 'u4EANiNxwS6C' | passwd --stdin support
        env_vars:
         - "NODE_TYPE=MESSAGE_ROUTING_NODE"
         - "SSHD_PORT=2222"
         - "ALWAYS_DIE_ON_FAILURE=1"
        net: host
        privileged: true
        uts: host
        volumes:
        - /dev/shm:/dev/shm
- name: vmr-config-job
  templates:
  -  {name: config_vmr, release: solace-vmr}
  lifecycle: errand
  instances: 1
  resource_pool: common-resource-pool
  networks:
  - name: test-network
    static_ips:
      - 10.244.0.2
  properties:
    starting_port: 7000
    broker_user: 'test_user-1212'
    broker_password: 'test_password-2323'
    broker_hostname: '10.254.50.4'
    admin_password: 'u4EANiNxwS6C'
    ssh_port: 2222
    dedicated_vmr_list:
      - 10.244.0.3
